-- Car makes reference table
CREATE TABLE car_makes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL UNIQUE,
    slug       VARCHAR(255) NOT NULL UNIQUE,
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE INDEX idx_car_makes_slug ON car_makes (slug);

-- Car models reference table
CREATE TABLE car_models (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(255) NOT NULL,
    slug       VARCHAR(255) NOT NULL,
    make_id    BIGINT       NOT NULL REFERENCES car_makes (id),
    version    BIGINT       NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

CREATE INDEX idx_car_models_make_id ON car_models (make_id);
CREATE INDEX idx_car_models_slug_make ON car_models (slug, make_id);

-- Core car listings table
CREATE TABLE car_listings (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- basic car info
    car_condition          VARCHAR(50)  NOT NULL,
    user_id                BIGINT       NOT NULL REFERENCES users (id),
    make_id                BIGINT       NOT NULL REFERENCES car_makes (id),
    model_id               BIGINT       NOT NULL REFERENCES car_models (id),
    seller_type            VARCHAR(50)  NOT NULL,
    year_of_manufacturing  DATE,
    plate_number           VARCHAR(255),
    mileage                INTEGER,
    car_type               VARCHAR(50),
    color                  VARCHAR(255),

    -- technical specification (embedded)
    engine_number          VARCHAR(255),
    chassis_number         VARCHAR(255),
    fuel_type              VARCHAR(50),
    transmission           VARCHAR(50),
    engine_capacity        INTEGER,
    horse_power            INTEGER,

    -- registration & ownership (embedded, prefixed to avoid collision)
    owner_name             VARCHAR(255),
    registration_date      DATE,
    number_of_transfers    INTEGER,
    reg_contact_number     VARCHAR(255),
    reg_email_address      VARCHAR(255),
    reg_address            VARCHAR(255),
    log_card_file_url      VARCHAR(1024),
    log_card_file_name     VARCHAR(255),
    log_card_mime_type     VARCHAR(255),
    log_card_size          BIGINT,

    -- price & COE details (embedded)
    asking_price           NUMERIC(15, 2),
    coe_renewal            DATE,
    coe_amount             NUMERIC(15, 2),
    down_payment           NUMERIC(15, 2),
    minimum_parf           NUMERIC(15, 2),
    depreciation           NUMERIC(15, 2),
    road_tax               NUMERIC(15, 2),
    omv                    NUMERIC(15, 2),

    -- ownership info (embedded, prefixed)
    registered_owner       VARCHAR(255),
    owner_contact_number   VARCHAR(255),
    owner_email            VARCHAR(255),
    owner_address          VARCHAR(255),
    is_seller              BOOLEAN,

    -- seller info (embedded, prefixed)
    seller_name            VARCHAR(255),
    seller_contact_number  VARCHAR(255),
    whats_app_number       VARCHAR(255),
    company_address        VARCHAR(255),
    seller_email           VARCHAR(255),
    loa_file_url           VARCHAR(1024),
    loa_file_name          VARCHAR(255),
    loa_mime_type          VARCHAR(255),
    loa_size               BIGINT,

    -- auditing
    version                BIGINT       NOT NULL DEFAULT 0,
    created_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by             VARCHAR(255),
    updated_by             VARCHAR(255)
);

CREATE INDEX idx_car_listings_user_id       ON car_listings (user_id);
CREATE INDEX idx_car_listings_make_id       ON car_listings (make_id);
CREATE INDEX idx_car_listings_model_id      ON car_listings (model_id);
CREATE INDEX idx_car_listings_car_condition ON car_listings (car_condition);

-- Car images table
CREATE TABLE car_images (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id         BIGINT        NOT NULL REFERENCES car_listings (id),
    image_url          VARCHAR(1024) NOT NULL,
    file_name          VARCHAR(255)  NOT NULL,
    mime_type          VARCHAR(255)  NOT NULL,
    size               BIGINT,
    number_plate_image BOOLEAN       NOT NULL DEFAULT false,
    version            BIGINT        NOT NULL DEFAULT 0,
    created_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    created_by         VARCHAR(255),
    updated_by         VARCHAR(255)
);

CREATE INDEX idx_car_images_listing_id ON car_images (listing_id);

-- Listing attributes for extensible key-value pairs
CREATE TABLE listing_attributes (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    listing_id      BIGINT       NOT NULL REFERENCES car_listings (id),
    attribute_key   VARCHAR(255) NOT NULL,
    attribute_value TEXT,
    version         BIGINT       NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by      VARCHAR(255),
    updated_by      VARCHAR(255)
);

CREATE INDEX idx_listing_attributes_listing_id ON listing_attributes (listing_id);
